### PR TITLE
(WEB-20) Set up Sinatra to serve static index with access to js libra…

### PR DESCRIPTION
**Pull request by pmpokorny**
…ries installed by Bower

### CODE REVIEW

**Comment by pmpokorny** [comment]
Fyi, this should run a simple "Hello Team B!" by running rackup at the command line.

**Comment by pmpokorny** [comment]
Sorry about the extra merge commit, something got backwards when I was amending...

**Comment by whopper** [comment]
@pmpokorny I like the look of these but I think we should resolve the merge conflict weirdness in this PR before we can merge. Perhaps some rebase surgery will do the trick?

**Comment by pmpokorny** [comment]
Git rebase interactive with a squash and then a forced push seem to have done the trick...
You might want to look things over before a merge though, this bit of surgery was pushing the envelope of truly safe operations for my skill level on git, so I do not 100% trust it.

**Comment by whopper** [comment]
@pmpokorny good work, that looks correct! However, it looks like you removed `bootstrap.js`, which I believe we'll still need underneath the bootstrap cosmo theme. That JS handles all of the nifty little interactive features of bootstrap (dropdown menus, popups, etc).

**Pull request merged**
