### PR TITLE
(WEB-21) add D3.js to project

### PR DESCRIPTION
**Pull request by cthelander**
Added D3.js to project

### CODE REVIEW

**Comment by whopper** [comment]
:+1:

**Comment by pmpokorny** [comment]
We may need to redo this by installing via bower, since that is the way react, react-bootstrap and reflux are almost certainly going to be installed. https://github.com/Team-B-Capstone/S-Pi-Web/pull/5
No hurry though, we can discuss it first.

**Comment by whopper** [comment]
@cthelander @pmpokorny yeah, sounds like we'll want to redo this the bower way

**Comment by whopper** [comment]
@cthelander I went ahead and did the equivalent to this via Bower here: https://github.com/Team-B-Capstone/S-Pi-Web/pull/6

**Pull request closed without merging**
